Feature/sc 67467/proper error handling for payments php and
publicsquare-financial/publicsquare-magento-payments-plugin pull request #10
Opened 2024-10-18 04:07 UTC by abrahambosch

2024-10-21 14:45 UTC, rlfrahm requested changes

2024-10-22 14:47 UTC, abrahambosch commented on PublicSquare/Payments/Model/Api/Payments.php
> +    private
`private` and `function` should be on the same line. I don't know how that happened.

2024-10-22 14:52 UTC, rlfrahm requested changes

2024-10-22 14:52 UTC, rlfrahm commented on PublicSquare/Payments/Model/Api/Payments.php
> +            // $this->logger->error($e->getMessage(), ['trace' => $e->getTraceAsString()]);
Remove these comments

2024-10-22 14:52 UTC, rlfrahm commented on PublicSquare/Payments/Model/Api/Payments.php
>              // $this->logError($e->getMessage(), $e->getTraceAsString());
Remove this comment

2024-10-22 14:52 UTC, rlfrahm commented on PublicSquare/Payments/Model/Api/Payments.php
> +            //throw new \Magento\Framework\Exception\PaymentException(new \Magento\Framework\Phrase($e->getMessage()));
Remove this comment

2024-10-22 14:55 UTC, rlfrahm approved these changes

2024-10-22 14:55 UTC, merged